machine:
  timezone:
    Europe/London

  python:
    version: 3.6.2

  environment:
    DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/circle_test

dependencies:
  pre:
    - pip install -r requirements.txt

database:
  override:
    # replace CircleCI's generated database.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake db:create db:schema:load

test:
  override:
    - pytest
