# CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2

    branches:
      ignore:
        - dokku

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
          environment:
            DATABASE_URL: "postgres://postgres:@localhost:5432/postgres"
